// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz5iMNN_r5opK99xN0zODxPoiFz-YNbUg',
    appId: '1:779308579241:web:ef7f03ad5cc9e04515acb8',
    messagingSenderId: '779308579241',
    projectId: 'coffee-app-bonus',
    authDomain: 'coffee-app-bonus.firebaseapp.com',
    storageBucket: 'coffee-app-bonus.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcWPkppinw6maAT9CYfFcZqzX3McYnMwY',
    appId: '1:779308579241:android:73931a4854b7bc2f15acb8',
    messagingSenderId: '779308579241',
    projectId: 'coffee-app-bonus',
    storageBucket: 'coffee-app-bonus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd3v7lrmFp9pzRkKrr2E3t-1A2MJHEMK4',
    appId: '1:779308579241:ios:7cbfd7b86b2ace4c15acb8',
    messagingSenderId: '779308579241',
    projectId: 'coffee-app-bonus',
    storageBucket: 'coffee-app-bonus.firebasestorage.app',
    iosBundleId: 'com.example.summerIubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd3v7lrmFp9pzRkKrr2E3t-1A2MJHEMK4',
    appId: '1:779308579241:ios:7cbfd7b86b2ace4c15acb8',
    messagingSenderId: '779308579241',
    projectId: 'coffee-app-bonus',
    storageBucket: 'coffee-app-bonus.firebasestorage.app',
    iosBundleId: 'com.example.summerIubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz5iMNN_r5opK99xN0zODxPoiFz-YNbUg',
    appId: '1:779308579241:web:d75fb986dbee30ef15acb8',
    messagingSenderId: '779308579241',
    projectId: 'coffee-app-bonus',
    authDomain: 'coffee-app-bonus.firebaseapp.com',
    storageBucket: 'coffee-app-bonus.firebasestorage.app',
  );
}
